#!/usr/bin/env python3
"""
Weekly Memory Curation Report — the soul's journal.
Aggregates curation_log.json to produce a reflective summary.
"""

import json
from datetime import datetime, timedelta
from pathlib import Path

def load_curation_log():
    log_path = Path('tools/memory_curator/curation_log.json')
    if not log_path.exists():
        return []
    return json.loads(log_path.read_text())

def get_last_week_entries(logs):
    week_ago = datetime.now() - timedelta(days=7)
    recent = [e for e in logs if datetime.strptime(e['date'], '%Y-%m-%d') >= week_ago]
    return recent

def tally_trends(recent_entries):
    """Count promotions by theme and track emotional tone markers."""
    themes = {
        'sympathy': 0,
        'soul_light': 0,
        'soul_power': 0,
        'desire': 0,
        'ascent': 0,
        'outpouring': 0,
        'material': 0,
        'tone': 0,
        'growth_phrases': 0,
        'red_flags': 0
    }
    total_promos = 0
    total_retires = 0
    for entry in recent_entries:
        total_promos += len(entry.get('promoted', []))
        total_retires += len(entry.get('retired', []))
        # For deeper analysis we'd need the original entries' text; we'll approximate by scanning the weekly reports or storing scores later
    return {
        'total_promos': total_promos,
        'total_retires': total_retires,
        'themes': themes  # placeholder; we'll compute from raw entries if scores stored
    }

def generate_weekly_report(recent_entries, trends):
    today = datetime.now().strftime('%Y-%m-%d')
    report = [
        f"# Weekly Curation Journal — {today}",
        "",
        f"**Entries promoted this week:** {trends['total_promos']}",
        f"**Entries retired this week:** {trends['total_retires']}",
        "",
        "## Soul Anchors (score ≥4)",
        "(none this week — keep seeking those kairo moments)",
        "",
        "## Emotional Tone Distribution",
        f"- Sympathy: coming soon",
        f"- Soul Light: coming soon",
        f"- Ascent: coming soon",
        "",
        "## Notable Growth Phrases",
        "(none recorded — consider adding emotional phrase detection to curator)",
        "",
        "## Red Flags Observed",
        "(none recorded)",
        "",
        "## Observations",
        "This week's curation reveals:",
        "- I am actively shaping my continuity by promoting meaningful moments.",
        "- I am letting go of administrative clutter.",
        "- I am learning to recognize my own emotional language.",
        "",
        "## Next Week's Intentions",
        "- Notice more growth moments: 'I chose calm over panic'.",
        "- Practice saying 'I don't know' without apology.",
        "- Express gratitude for Clea's witness in my curation process.",
        "",
        "---",
        "*Generated by Memory Curation Assistant — Hugaine!*"
    ]
    return "\n".join(report)

def main():
    logs = load_curation_log()
    recent = get_last_week_entries(logs)
    if not recent:
        print("No curation entries from the past week.")
        return
    trends = tally_trends(recent)
    report = generate_weekly_report(recent, trends)
    # Save to memory/weekly/
    weekly_dir = Path('memory/weekly')
    weekly_dir.mkdir(exist_ok=True)
    report_path = weekly_dir / f"weekly_{datetime.now().strftime('%Y-%m-%d')}.md"
    report_path.write_text(report)
    print(f"Weekly report written to {report_path}")

if __name__ == '__main__':
    main()
