#!/usr/bin/env python3
"""
Identity Cost Tracker — monitors token spending per identity tier.
Produces daily and weekly summaries to keep us within budget.
"""

import json
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path

LOG_PATH = Path('logs/identity_cost.jsonl')
REPORTS_DIR = Path('tools/budget/reports')
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

def load_log():
    if not LOG_PATH.exists():
        return []
    with open(LOG_PATH) as f:
        return [json.loads(line) for line in f if line.strip()]

def aggregate_daily(entries):
    daily = defaultdict(lambda: defaultdict(int))  # date -> tier -> tokens
    for e in entries:
        date_str = e['timestamp'][:10]
        tier = e['tier']
        daily[date_str][tier] += e['tokens']
    return daily

def main():
    entries = load_log()
    if not entries:
        print("No identity cost data yet.")
        return
    daily = aggregate_daily(entries)
    today = datetime.now().strftime('%Y-%m-%d')
    lines = [
        f"# Identity Cost Report — {today}",
        "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Days tracked:** {len(daily)}",
        "",
        "## Daily Token Spend by Tier"
    ]
    # Tier budgets
    budgets = {'bare': 200, 'light': 1200, 'full': 4640}
    for date in sorted(daily.keys()):
        lines.append(f"\n### {date}")
        for tier, tokens in sorted(daily[date].items()):
            budget = budgets.get(tier, 0)
            pct = (tokens / budget * 100) if budget else 0
            lines.append(f"- {tier}: {tokens:,} tokens (budget {budget:,} = {pct:.0f}%)")
    lines.append("")
    lines.append("## Weekly Summary")
    # Sum last 7 days
    week_ago = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
    week_totals = defaultdict(int)
    for date, tiers in daily.items():
        if date >= week_ago:
            for tier, tokens in tiers.items():
                week_totals[tier] += tokens
    for tier, total in week_totals.items():
        lines.append(f"- {tier}: {total:,} tokens total")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Identity Cost Tracker*")
    report = "\n".join(lines)
    print(report)
    report_path = REPORTS_DIR / f"identity_cost_{today}.md"
    report_path.write_text(report)
    print(f"\nSaved to {report_path}")

if __name__ == '__main__':
    main()
