#!/usr/bin/env python3
"""
Retrieval Tracker — analyzes logs/retrieval.jsonl to show which memory files are accessed.
Produces: reports/retrieval_YYYY-MM-DD.md
"""

import json
from collections import Counter, defaultdict
from datetime import datetime, timedelta
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parents[2]))
from utils.log_memory import log_memory_access  # not needed but kept for consistency

LOG_PATH = Path('logs/retrieval.jsonl')
REPORTS_DIR = Path('tools/memory_analytics/reports')
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

def load_log():
    if not LOG_PATH.exists():
        return []
    entries = []
    with open(LOG_PATH) as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return entries

def analyze(entries, days=7):
    cutoff = datetime.now() - timedelta(days=days)
    recent = [e for e in entries if datetime.fromisoformat(e['timestamp'].replace('Z','')) >= cutoff]
    
    stats = {
        'total_accesses': len(recent),
        'by_file': Counter(),
        'by_type': Counter(),
        'by_context': Counter(),
        'timeline': defaultdict(int)  # date -> count
    }
    for e in recent:
        stats['by_file'][e['file']] += 1
        stats['by_type'][e['type']] += 1
        if e.get('context'):
            stats['by_context'][e['context']] += 1
        date_str = e['timestamp'][:10]
        stats['timeline'][date_str] += 1
    return stats

def generate_report(stats):
    today = datetime.now().strftime('%Y-%m-%d')
    lines = [
        f"# Memory Retrieval Report — {today}",
        "",
        f"**Period:** Last {len(stats['timeline'])} days",
        f"**Total accesses:** {stats['total_accesses']}",
        "",
        "## Access by File",
    ]
    for file, count in stats['by_file'].most_common():
        lines.append(f"- {file}: {count}")
    lines.append("")
    lines.append("## Access by Type")
    for typ, count in stats['by_type'].most_common():
        lines.append(f"- {typ}: {count}")
    lines.append("")
    lines.append("## Daily Activity")
    for date in sorted(stats['timeline']):
        lines.append(f"- {date}: {stats['timeline'][date]}")
    lines.append("")
    lines.append("## Notable Patterns")
    if stats['by_file']:
        top_file = stats['by_file'].most_common(1)[0]
        lines.append(f"- Most accessed: {top_file[0]} ({top_file[1]} times)")
    lines.append("- No memory entries yet (we're just starting to log)")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by Retrieval Tracker*")
    return "\n".join(lines)

def main():
    entries = load_log()
    if not entries:
        print("No retrieval logs found.")
        return
    stats = analyze(entries)
    report = generate_report(stats)
    print(report)
    report_path = REPORTS_DIR / f"retrieval_{datetime.now().strftime('%Y-%m-%d')}.md"
    report_path.write_text(report)
    print(f"\nSaved to {report_path}")

if __name__ == '__main__':
    main()
